### ISSUE TITLE
callAttachHook execute twice.

### ISSUE THREAD

**Issue by DC3** [atom/space-pen#16]
When i use `prependTo`, `appendTo`, `insertAfter`, `insertBefore` method, callAttachHook execute twice.

But use `append`, `prepend`, `after`, `before` method, hooks just execute once.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
