### ISSUE TITLE
Subclassing

### ISSUE THREAD

**Issue by horatio-sans-serif** [atom/space-pen#22]
I tried to create a convenience for myself in a ModelView subclass of View that my models will subclass (e.g. UserView).

As a simplified example:

``` coffeescript
class ModelView extends View
  constructor: (@model, @mutable) -> super @model, @mutable
  @propertyView: (property, klass, label) ->
    @subview property, new klass { @model, property, label, @mutable }

class UserView extends ModelView
  @content: ->
    @propertyView 'firstName', TextView

class TextView extends View
  @content: (params) -> @input params.model.get params.property

class User:  # a model, say from Parse
  get: (property) -> 'Brian'  # whatever

me = new User
me.set 'firstName', 'Brian'

$('body').append (new UserView me, yes)
```

However, this isn't working as expected and I could use a push in the right direction since I'm new to CoffeeScript and SpacePen.  

The error is that in TextView, params.model is undefined. 

As I expected, in the constructor of ModelView, @model is being saved as an instance var.

``` javascript
    function ModelView(model, mutable) {
     this.model = model;
     this.mutable = mutable;
     ModelView.__super__.constructor.call(this, this.model, this.mutable);
    }
```

The View constructor calls @content immediately so it seems that @model is not being set after all?  I think I'm a bit confused why the content is @content (static property) and not 'content' ... What am I missing? Thanks!

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
