### ISSUE TITLE
Compiling to js

### ISSUE THREAD

**Issue by babsonmatt** [atom/space-pen#24]
Any docs regarding how to compile and serve the coffee view files as JS?

Thanks!

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
