### ISSUE TITLE
@subview in top level of given view 

### ISSUE THREAD

**Issue by fentas** [atom/space-pen#48]
Hi there
if you use a subview in root level of a view it does not work. Like this:

``` coffee
$('.other-class').append $$ ->
  @div id: 'foobar', =>
        @button class: 'btn selected', 'data-display-class': 'show-bar', 'bar'
        @button class: 'btn', 'data-display-class': 'show-data', 'data'
  @subview '__', [subview...]
```

I digged into it and found what could be the problem. Within `Builder.prototype.subview` there is following part which will not work with the example above:

``` js
      return this.postProcessingSteps.push(function(view) {
        view[outletName] = subview;
        subview.parentView = view;
        return view.find("div#" + subviewId).replaceWith(subview);
      });
```

The returned `view` contains all the root elements (here: `div#foobar`, `div#subview-\d+`).
Now `.find(...)` tries to _find_ `div#subview-\d+` but as it is one of the root elements it can't **find** it.

A workaround for me was simply to add a div around the subview. But you have to know that first. : )

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
