### ISSUE TITLE
How apply event click to content add by append?

### ISSUE THREAD

**Issue by fuechter** [atom/space-pen#54]
```
@checklists.append "<div class='item'>#{description}</div>"
```

How apply event click on item that append on checklists?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
