### ISSUE TITLE
atom-text-editor in @tag

### ISSUE THREAD

**Issue by Raynes** [atom/space-pen#57]
I was playing around and tried to do `@tag 'atom-text-editor', <stuff>` and it complains with a very specific error indicating that because it is a custom element inheritance needs to be used.

Any way to make that work?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
