### ISSUE TITLE
Can't have an outlet on the top level

### ISSUE THREAD

**Issue by Raynes** [atom/space-pen#58]
I tried to do:

``` coffeescript
@content: ->
  @div outlet: 'foo'
```

Much to my chagrin, `@foo` was not accessible. If I put an outlet on a nested div, it works fine. Is this intended?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
