### ISSUE TITLE
Does not play well when multiple versions of spacepen

### ISSUE THREAD

**Issue by benogle** [atom/space-pen#60]
In converting find and replace, I am getting this error:

![screen shot 2014-11-26 at 5 51 43 pm](https://cloud.githubusercontent.com/assets/69169/5211349/09c0d952-7595-11e4-8021-0fd500b24118.png)

I assume this is because I have a different version than that of some other package who got to registering this tag. Looks like there is no method to check if the element has been registered. I suppose we could try/catch. My guess is that this will happen in the wild.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
